---
- name: Deploy Spring Boot
  hosts: app
  vars:
    ci_cd_namespace: puckboard-demo-ci-cd
    dev_namespace: puckboard-demo-dev
    demo_namespace: puckboard-demo-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier