---
- name: Deploy Spring Boot
  hosts: app
  vars:
    ci_cd_namespace: labs-ci-cd-hshahin
    dev_namespace: labs-dev-hshahin
    demo_namespace: labs-test-hshahin
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier