---
- name: Deploy Spring Boot
  hosts: app
  vars:
    ci_cd_namespace: labs-ci-cd-phildemo
    dev_namespace: labs-dev-phildemo
    demo_namespace: labs-test-phildemo
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier