---
- name: Deploy Spring Boot
  hosts: app
  vars:
    ci_cd_namespace: labs-hs-ci-cd
    dev_namespace: labs-hs-dev
    demo_namespace: labs-hs-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier